template_path = "templates/*"
[[domains]]
email_domain = "localhost"
ssl_cert ="/etc/ssl/cert.pem"
ssl_key = "/etc/ssl/chain.pem"
ssl_chain = "/etc/ssl/private/key.pem"
display_name = "localhost mail service"
display_short_name = "localhost email"
allowed_hosts = [
    "localhost"
]
[domains.smtp]
host = "smtp.localhost"
port = 465
socket_type = "SSL"
[domains.imap]
host = "imap.localhost"
port = 993
socket_type = "SSL"
