template_path = "templates/*"
socket_address = "127.0.0.1:3000"
# Uncomment to reload the server on file change
# watch_path = "some_path/"
[[domains]]
email_domain = "localhost"
# Could also contain only the end certificate if you do not want to provide a chain
ssl_chain ="/etc/ssl/chain.pem"
ssl_key = "/etc/ssl/chain.pem"
display_name = "localhost mail service"
display_short_name = "localhost email"
allowed_hosts = [
    "localhost"
]
[domains.smtp]
host = "smtp.localhost"
port = 465
socket_type = "SSL"
[domains.imap]
host = "imap.localhost"
port = 993
socket_type = "SSL"
